EMPTY_TILE = 0
TILE_SET_ADDR
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0
    .byte 0,0,0,0,0,0,0,0


HEAD_R_TILE = 1
HEAD_RIGHT
    .byte HEAD_COL,HEAD_COL,0,0,HEAD_COL,HEAD_COL,HEAD_COL,0
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0,0,HEAD_COL
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0,0
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0,0
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0,0
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0,0
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0,0,HEAD_COL
    .byte HEAD_COL,HEAD_COL,0,0,HEAD_COL,HEAD_COL,HEAD_COL,0

HEAD_L_TILE = 2
HEAD_LEFT
    .byte 0,HEAD_COL,HEAD_COL,HEAD_COL,0,0,HEAD_COL,HEAD_COL
    .byte HEAD_COL,0,0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte 0,0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte 0,0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL    
    .byte 0,0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte 0,0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte HEAD_COL,0,0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte 0,HEAD_COL,HEAD_COL,HEAD_COL,0,0,HEAD_COL,HEAD_COL

HEAD_U_TILE = 3
HEAD_UP
    .byte 0,HEAD_COL,0,0,0,0,HEAD_COL,0
    .byte HEAD_COL,0,0,0,0,0,0,HEAD_COL
    .byte HEAD_COL,0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0,HEAD_COL
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte 0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0
    .byte 0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL

HEAD_D_TILE = 4
HEAD_DOWN
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte 0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0
    .byte 0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0
    .byte HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL
    .byte HEAD_COL,0,HEAD_COL,HEAD_COL,HEAD_COL,HEAD_COL,0,HEAD_COL
    .byte HEAD_COL,0,0,0,0,0,0,HEAD_COL
    .byte 0,HEAD_COL,0,0,0,0,HEAD_COL,0


.include "auto_tiles.inc"


